### ISSUE TITLE
Usable variables

### ISSUE THREAD

**Issue by Tchoupinax** [appleboy/drone-discord#20]
Hello,

I would like to know why i can use some variable but not all.
For example, i would like to use [commit.message](https://github.com/appleboy/drone-discord/blob/98665b9a28404f068ac998a3f7f42c701008b05b/main.go#L129) but it returns blank.
However others variables that are declared on this [page](http://plugins.drone.io/appleboy/drone-discord/) are usable (like build.number).

Do you know why ? 
Thank you for your work :)

Regards,

**Comment by appleboy** [comment]
I add the example. See the following.

https://github.com/appleboy/drone-discord/blob/fe2b53fab47bb71c9df34482f4227e1c30cd0878/.drone.yml#L346-L354
