### ISSUE TITLE
Variables build.started and build.finished and Duration Not Working

### ISSUE THREAD

**Issue by jimmybrancaccio** [appleboy/drone-discord#30]
This is a continuation of [#22](https://github.com/appleboy/drone-discord/issues/22#issuecomment-606757958). I am trying to use the following at the end of my `.drone.yml` file:

```
- name: discord notification
  when:
    status:
      - success
      - failure
  image: appleboy/drone-discord
  settings:
  webhook_id: 1234567890
  webhook_token: 123456789012345678901234567890
  message: "{{#success build.status}}✅ **mangos-classic - Build #{{build.number}}**\n- Started at {{datetime build.started \"2006-01-02 15:04:05\" \"America/Chicago\"}} and finished at {{datetime build.finished \"2006-01-02 15:04:05\" \"America/Chicago\"}}\n- Build Duration: {{duration build.started build.finished}}\n{{build.link}}{{else}}❌ **mangos-classic - Build #{{build.number}}\n- Started at {{datetime build.started \"2006-01-02 15:04:05\" \n\"America/Chicago\"}} and finished at {{datetime build.finished \"2006-01-02 15:04:05\" \"America/Chicago\"}}\n- Build Duration: {{duration build.started build.finished}}\n{{build.link}}{{/success}}"
```

However it's not obeying the timezone I have set (America/Chicago) and is showing times in UTC (which I noted also happens in the example you provided in #22), and the `build.started` and `build.finished` are showing the same times.

The duration is also showing 0s, likely because `build.started` and `build.finished` are both the same time.

Any ideas on these issues?

**Comment by appleboy** [comment]
I don't have any idea. I try the cloud.drone.io. It is working.

**Comment by jimmybrancaccio** [comment]
@appleboy I just tried using cloud.drone.io and it does not work there either.

<img width="641" alt="Screen Shot 2020-06-10 at 1 07 23 PM" src="https://user-images.githubusercontent.com/405585/84302725-64b0da80-ab1b-11ea-8072-190c9af41cba.png">

Both same started and finished times, duration is 0s and timezone is still UTC.

**Comment by appleboy** [comment]
@jimmybrancaccio Can you help to try the latest version?

![Screen Shot 2020-07-23 at 12 20 49 PM](https://user-images.githubusercontent.com/21979/88251938-0b71c480-ccdf-11ea-87ae-58a2c5e0ece0.png)

**Comment by jimmybrancaccio** [comment]
@appleboy I actually ended up creating my own Discord plugin as I was too frustrated with this one not working.

**Comment by haliliceylan** [comment]
i have same error, its still showing 0. I am using docker pipeline.
