### ISSUE TITLE
Setup always reported success on Kubernetes

### ISSUE THREAD

**Issue by kradalby** [appleboy/drone-discord#31]
Hi

I posted on discourse earlier today here: https://discourse.drone.io/t/notification-plugins-always-reports-success/7538

Basically I have switched to running my pipelines with the Kubernetes runner and it has changed how step information is passed from one to another. 
So the discord plugin will always report success.

And there is a known limitation in drone, https://docs.drone.io/runner/kubernetes/overview/#known-issues--differences

Is this something that would be possible to fix?

**Comment by appleboy** [comment]
@kradalby fixed in 5804cc4e3

**Comment by appleboy** [comment]
@kradalby Please try the latest version

**Comment by appleboy** [comment]
See https://github.com/appleboy/drone-discord/releases/tag/v1.2.5

**Comment by kradalby** [comment]
Looks great, thanks!
