### ISSUE TITLE
Where to get the token and the webhook id?

### ISSUE THREAD

**Issue by iddm** [appleboy/drone-discord#7]
I can't understand, where may I get those? I have created a webhook in the client and there is a link only.

**Comment by jeroen-plug** [comment]
The link contains both the id and the token.
//discordapp.com/api/webhooks/{webhook.id}/{webhook.token}

see: https://discordapp.com/developers/docs/resources/webhook#get-webhook-with-token

**Comment by iddm** [comment]
Thanks, i figured that out :)
